/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlterationRequest {
  'id' : string,
  'status' : string,
  'estimatedPrice' : bigint,
  'description' : string,
  'garmentType' : string,
  'customerId' : Principal,
  'requestTime' : Time,
  'photos' : Array<string>,
}
export interface Appointment {
  'id' : string,
  'status' : string,
  'serviceType' : string,
  'createdTime' : Time,
  'notes' : string,
  'customerId' : Principal,
  'dateTime' : Time,
}
export interface Customer {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'preferences' : string,
  'measurements' : string,
  'phone' : string,
}
export interface Order {
  'id' : string,
  'paymentStatus' : string,
  'orderTime' : Time,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'shippingDetails' : ShippingDetails,
}
export interface OrderItem { 'productId' : string, 'quantity' : bigint }
export interface Product {
  'id' : string,
  'categories' : Array<string>,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'images' : Array<string>,
}
export interface ShippingDetails {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'address' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'preferences' : string,
  'measurements' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlterationRequest' : ActorMethod<[AlterationRequest], string>,
  'createAppointment' : ActorMethod<[Appointment], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateCustomer' : ActorMethod<[Customer], undefined>,
  'createOrder' : ActorMethod<[Order], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAlterationRequestById' : ActorMethod<[string], AlterationRequest>,
  'getAlterationRequestsByCustomer' : ActorMethod<
    [Principal],
    Array<AlterationRequest>
  >,
  'getAppointmentById' : ActorMethod<[string], Appointment>,
  'getAppointmentsByCustomer' : ActorMethod<[Principal], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerById' : ActorMethod<[Principal], Customer>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAlterationRequestStatus' : ActorMethod<[string, string], undefined>,
  'updateAppointmentStatus' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];